import type { TextAnimation, TextOverlay } from '@/engine/types'
import { loadGoogleFont } from '@/lib/fonts'

export type TypographyCategory =
  | 'All'
  | 'Viral & Hooks'
  | 'Essential'
  | 'Cinematic'
  | 'Tech & Cyber'
  | 'Creative'
  | 'Badges'

export const TYPOGRAPHY_CATEGORIES: TypographyCategory[] = [
  'All',
  'Viral & Hooks',
  'Essential',
  'Cinematic',
  'Tech & Cyber',
  'Creative',
  'Badges',
]

export interface TextTypographyPreset {
  id: string
  name: string
  category: Exclude<TypographyCategory, 'All'>
  text: string
  fontSize: number
  fontFamily: string
  fontWeight: string | number
  fontStyle?: 'normal' | 'italic'
  color: string
  backgroundColor: string
  animation: TextAnimation
  animationDuration?: number
  textAlign?: 'left' | 'center' | 'right'
  letterSpacing?: number
  lineHeight?: number
  textTransform?: 'none' | 'uppercase' | 'lowercase' | 'capitalize'
  textDecoration?: 'none' | 'underline' | 'line-through'
  stroke?: { width: number; color: string }
  shadow?: boolean
  shadowColor?: string
  shadowBlur?: number
  shadowOffsetX?: number
  shadowOffsetY?: number
  borderRadius?: number
  paddingTop?: number
  paddingBottom?: number
  paddingLeft?: number
  paddingRight?: number
  description: string
}

export const TEXT_TYPOGRAPHY_PRESETS: TextTypographyPreset[] = [
  // ─── Essential (6) ────────────────────────────────────────────────────────
  {
    id: 'heading-bold',
    name: 'Bold Headline',
    category: 'Essential',
    text: 'YOUR TITLE HERE',
    fontSize: 56,
    color: '#ffffff',
    backgroundColor: 'transparent',
    fontFamily: 'Inter',
    animation: 'fade-in',
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    description: 'High-impact modern uppercase headline',
  },
  {
    id: 'subtitle-clean',
    name: 'Subtitle / Description',
    category: 'Essential',
    text: 'A clean supporting description or subtitle',
    fontSize: 28,
    color: '#e2e8f0',
    backgroundColor: 'transparent',
    fontFamily: 'Inter',
    animation: 'slide-up',
    fontWeight: '500',
    description: 'Crisp body and narration copy',
  },
  {
    id: 'minimal-caption',
    name: 'Minimal Caption',
    category: 'Essential',
    text: 'Minimal clean title design',
    fontSize: 32,
    color: '#ffffff',
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    fontFamily: 'Plus Jakarta Sans',
    animation: 'fade-in',
    fontWeight: '600',
    borderRadius: 6,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 14,
    paddingRight: 14,
    description: 'Sleek dark translucent badge',
  },
  {
    id: 'editorial-deck',
    name: 'Editorial Deck',
    category: 'Essential',
    text: 'THE INSIDE PERSPECTIVE',
    fontSize: 34,
    color: '#f8fafc',
    backgroundColor: 'transparent',
    fontFamily: 'Lora',
    animation: 'fade-in',
    fontWeight: '600',
    letterSpacing: 2,
    textTransform: 'uppercase',
    description: 'Refined editorial deck and sub-heading',
  },
  {
    id: 'modern-bold-serif',
    name: 'Statement Serif',
    category: 'Essential',
    text: 'MODERN STATEMENT',
    fontSize: 48,
    color: '#ffffff',
    backgroundColor: 'transparent',
    fontFamily: 'Merriweather',
    animation: 'slide-up',
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    description: 'Punchy modern serif statement title',
  },
  {
    id: 'micro-chapter',
    name: 'Chapter Micro Tag',
    category: 'Essential',
    text: 'CHAPTER 01 // INTRODUCTION',
    fontSize: 22,
    color: '#94a3b8',
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    fontFamily: 'Outfit',
    animation: 'fade-in',
    fontWeight: '800',
    letterSpacing: 3,
    borderRadius: 4,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 12,
    paddingRight: 12,
    textTransform: 'uppercase',
    description: 'Technical chapter and micro header badge',
  },

  // ─── Viral & Hooks (7) ────────────────────────────────────────────────────
  {
    id: 'viral-yellow-hook',
    name: 'Viral TikTok Hook',
    category: 'Viral & Hooks',
    text: 'WAIT TILL THE END! ⚡',
    fontSize: 52,
    color: '#facc15',
    backgroundColor: 'transparent',
    fontFamily: 'Oswald',
    animation: 'pop',
    fontWeight: '700',
    stroke: { width: 3.5, color: '#000000' },
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.95)',
    shadowBlur: 8,
    description: 'High-contrast yellow punch for short-form retention',
  },
  {
    id: 'reels-punchy-bold',
    name: 'Reels Punchy Outline',
    category: 'Viral & Hooks',
    text: '3 SECRETS REVEALED',
    fontSize: 54,
    color: '#ffffff',
    backgroundColor: 'transparent',
    fontFamily: 'Bebas Neue',
    animation: 'pop',
    fontWeight: '400',
    letterSpacing: 2,
    stroke: { width: 3.5, color: '#ef4444' },
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 6,
    description: 'Bold red outline typography for attention',
  },
  {
    id: 'mrbeast-bold-glow',
    name: 'MrBeast Subtitle',
    category: 'Viral & Hooks',
    text: 'I SPENT $1,000,000!',
    fontSize: 58,
    color: '#ffffff',
    backgroundColor: 'transparent',
    fontFamily: 'Anton',
    animation: 'pop',
    fontWeight: '400',
    letterSpacing: 1,
    stroke: { width: 4.5, color: '#000000' },
    shadow: true,
    shadowColor: '#22c55e',
    shadowBlur: 16,
    description: 'Ultra-bold high contrast gaming & viral hook style',
  },
  {
    id: 'hormozi-highlighter',
    name: 'Hormozi Highlighter',
    category: 'Viral & Hooks',
    text: 'DO NOT MAKE THIS MISTAKE',
    fontSize: 46,
    color: '#000000',
    backgroundColor: '#facc15',
    fontFamily: 'Montserrat',
    animation: 'pop',
    fontWeight: '900',
    borderRadius: 4,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    paddingRight: 16,
    letterSpacing: 1,
    textTransform: 'uppercase',
    description: 'Alex Hormozi high-contrast highlighter backdrop',
  },
  {
    id: 'comic-banger',
    name: 'Comic Boom',
    category: 'Viral & Hooks',
    text: 'BOOM! MUST WATCH',
    fontSize: 50,
    color: '#fde047',
    backgroundColor: 'transparent',
    fontFamily: 'Bangers',
    animation: 'bounce',
    fontWeight: '400',
    stroke: { width: 4, color: '#000000' },
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 8,
    description: 'Playful comic-style pop for gaming and reaction clips',
  },
  {
    id: 'karaoke-dynamic-glow',
    name: 'Dynamic Karaoke Pop',
    category: 'Viral & Hooks',
    text: 'EVERY SINGLE WORD MATTERS',
    fontSize: 46,
    color: '#38bdf8',
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    fontFamily: 'Plus Jakarta Sans',
    animation: 'pop',
    fontWeight: '800',
    borderRadius: 8,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    paddingRight: 16,
    shadow: true,
    shadowColor: '#0284c7',
    shadowBlur: 14,
    description: 'Vibrant dynamic pop subtitle for fast-paced speech',
  },
  {
    id: 'scroll-stopper-alert',
    name: 'Scroll-Stopper Alert',
    category: 'Viral & Hooks',
    text: 'STOP SCROLLING 🚨',
    fontSize: 50,
    color: '#ef4444',
    backgroundColor: 'transparent',
    fontFamily: 'Anton',
    animation: 'pop',
    fontWeight: '400',
    stroke: { width: 3, color: '#ffffff' },
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 12,
    description: 'Urgent high-friction scroll-stopping hook',
  },

  // ─── Cinematic & Luxury (6) ───────────────────────────────────────────────
  {
    id: 'cinematic-gold',
    name: 'Cinematic Gold',
    category: 'Cinematic',
    text: 'A FILM BY CREATOR',
    fontSize: 42,
    color: '#fef08a',
    backgroundColor: 'transparent',
    fontFamily: 'Cinzel',
    animation: 'fade-in',
    fontWeight: '700',
    letterSpacing: 4,
    textTransform: 'uppercase',
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 10,
    description: 'Classic high-end movie title with wide tracking',
  },
  {
    id: 'luxury-editorial',
    name: 'Editorial Luxury',
    category: 'Cinematic',
    text: 'The Modern Aesthetic',
    fontSize: 40,
    color: '#f8fafc',
    backgroundColor: 'transparent',
    fontFamily: 'Playfair Display',
    animation: 'fade-in',
    fontStyle: 'italic',
    fontWeight: '600',
    description: 'Refined serif typography for documentaries & luxury brands',
  },
  {
    id: 'film-noir',
    name: 'Film Noir Classic',
    category: 'Cinematic',
    text: 'SHADOWS OF YESTERDAY',
    fontSize: 44,
    color: '#f1f5f9',
    backgroundColor: 'transparent',
    fontFamily: 'Bodoni Moda',
    animation: 'fade-in',
    fontWeight: '800',
    letterSpacing: 3,
    textTransform: 'uppercase',
    shadow: true,
    shadowColor: '#000000',
    shadowBlur: 16,
    description: 'Monochrome dramatic vintage cinema style',
  },
  {
    id: 'hollywood-trailer',
    name: 'Hollywood Teaser',
    category: 'Cinematic',
    text: 'COMING THIS SUMMER',
    fontSize: 48,
    color: '#e2e8f0',
    backgroundColor: 'transparent',
    fontFamily: 'Oswald',
    animation: 'fade-in',
    fontWeight: '600',
    letterSpacing: 5,
    textTransform: 'uppercase',
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 12,
    description: 'Wide-spaced blockbuster teaser trailer title',
  },
  {
    id: 'documentary-subhead',
    name: 'Modern Documentary',
    category: 'Cinematic',
    text: 'Voices from the deep north',
    fontSize: 30,
    color: '#cbd5e1',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    fontFamily: 'Lora',
    animation: 'fade-in',
    fontStyle: 'italic',
    fontWeight: '400',
    borderRadius: 4,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 12,
    paddingRight: 12,
    description: 'Intimate narrative voiceover caption',
  },
  {
    id: 'golden-prestige',
    name: 'Festival Laurels Gold',
    category: 'Cinematic',
    text: 'OFFICIAL SELECTION',
    fontSize: 36,
    color: '#eab308',
    backgroundColor: 'transparent',
    fontFamily: 'Cinzel',
    animation: 'fade-in',
    fontWeight: '900',
    letterSpacing: 3,
    stroke: { width: 1, color: '#713f12' },
    textTransform: 'uppercase',
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 8,
    description: 'Gold gilded film festival laurel title',
  },

  // ─── Tech & Cyberpunk (6) ─────────────────────────────────────────────────
  {
    id: 'neon-cyber',
    name: 'Cyberpunk Neon',
    category: 'Tech & Cyber',
    text: 'CYBERPUNK 2099',
    fontSize: 46,
    color: '#22d3ee',
    backgroundColor: 'transparent',
    fontFamily: 'Orbitron',
    animation: 'pop',
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
    shadow: true,
    shadowColor: '#06b6d4',
    shadowBlur: 16,
    description: 'Glowing sci-fi title with cyan neon aura',
  },
  {
    id: 'purple-vaporwave',
    name: 'Synthwave Glow',
    category: 'Tech & Cyber',
    text: 'RETRO HORIZON',
    fontSize: 46,
    color: '#c084fc',
    backgroundColor: 'transparent',
    fontFamily: 'Space Grotesk',
    animation: 'fade-in',
    fontWeight: '700',
    letterSpacing: 2,
    textTransform: 'uppercase',
    shadow: true,
    shadowColor: '#a855f7',
    shadowBlur: 14,
    description: 'Synthwave purple neon glow header',
  },
  {
    id: 'hacker-terminal',
    name: 'Hacker Terminal',
    category: 'Tech & Cyber',
    text: '> npm run build:success',
    fontSize: 26,
    color: '#4ade80',
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    fontFamily: 'JetBrains Mono',
    animation: 'typewriter',
    fontWeight: '600',
    borderRadius: 6,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 14,
    paddingRight: 14,
    description: 'Matrix green live developer terminal prompt',
  },
  {
    id: 'futuristic-hud',
    name: 'Sci-Fi HUD Readout',
    category: 'Tech & Cyber',
    text: 'SYS.OVERRIDE // 0x7F',
    fontSize: 28,
    color: '#38bdf8',
    backgroundColor: 'rgba(8, 47, 73, 0.75)',
    fontFamily: 'Space Mono',
    animation: 'typewriter',
    fontWeight: '700',
    letterSpacing: 2,
    stroke: { width: 1, color: '#0284c7' },
    borderRadius: 4,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 12,
    paddingRight: 12,
    description: 'Sci-Fi HUD tactical readout',
  },
  {
    id: 'silicon-valley',
    name: 'Silicon Valley Sans',
    category: 'Tech & Cyber',
    text: 'Next-Gen Intelligence',
    fontSize: 40,
    color: '#ffffff',
    backgroundColor: 'transparent',
    fontFamily: 'DM Sans',
    animation: 'fade-in',
    fontWeight: '700',
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 8,
    description: 'Clean modern SaaS tech brand headline',
  },
  {
    id: 'fira-code-snippet',
    name: 'Code Editor Snippet',
    category: 'Tech & Cyber',
    text: 'const magic = await render()',
    fontSize: 26,
    color: '#e879f9',
    backgroundColor: 'rgba(24, 24, 27, 0.92)',
    fontFamily: 'Fira Code',
    animation: 'slide-left',
    fontWeight: '500',
    borderRadius: 6,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 12,
    paddingRight: 12,
    description: 'Crisp code editor snippet overlay',
  },

  // ─── Creative & Handwritten (5) ───────────────────────────────────────────
  {
    id: 'handwritten-vlog',
    name: 'Handwritten Vlog',
    category: 'Creative',
    text: 'Day in my life ✨',
    fontSize: 40,
    color: '#fda4af',
    backgroundColor: 'transparent',
    fontFamily: 'Caveat',
    animation: 'fade-in',
    fontWeight: '700',
    description: 'Casual handwritten note for lifestyle and vlogs',
  },
  {
    id: 'signature-marker',
    name: 'Street Marker Pen',
    category: 'Creative',
    text: 'Behind The Scenes',
    fontSize: 42,
    color: '#fde047',
    backgroundColor: 'transparent',
    fontFamily: 'Permanent Marker',
    animation: 'pop',
    fontWeight: '400',
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 6,
    description: 'Bold street marker pen scribble',
  },
  {
    id: 'casual-script',
    name: 'Casual Roadtrip Script',
    category: 'Creative',
    text: 'Summer Roadtrip Diary',
    fontSize: 38,
    color: '#67e8f9',
    backgroundColor: 'transparent',
    fontFamily: 'Pacifico',
    animation: 'slide-up',
    fontWeight: '400',
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.7)',
    shadowBlur: 8,
    description: 'Playful beach and vacation script',
  },
  {
    id: 'retro-disco',
    name: '80s Retro Disco',
    category: 'Creative',
    text: 'SATURDAY NIGHT FEVER',
    fontSize: 44,
    color: '#f43f5e',
    backgroundColor: 'transparent',
    fontFamily: 'Lobster',
    animation: 'bounce',
    fontWeight: '400',
    stroke: { width: 2, color: '#ffe4e6' },
    shadow: true,
    shadowColor: '#be123c',
    shadowBlur: 14,
    description: '80s vintage disco flare typography',
  },
  {
    id: 'street-graffiti',
    name: 'Urban Poster Syne',
    category: 'Creative',
    text: 'UNDERGROUND BEATS',
    fontSize: 46,
    color: '#fbbf24',
    backgroundColor: 'transparent',
    fontFamily: 'Syne',
    animation: 'pop',
    fontWeight: '800',
    letterSpacing: 1,
    stroke: { width: 3, color: '#18181b' },
    shadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 10,
    textTransform: 'uppercase',
    description: 'Urban edgy street poster typography',
  },

  // ─── Badges & Lower Thirds (5) ────────────────────────────────────────────
  {
    id: 'lower-third-modern',
    name: 'Lower Third Pill',
    category: 'Badges',
    text: 'Piyush Mehta — Video Creator',
    fontSize: 24,
    color: '#38bdf8',
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    fontFamily: 'Plus Jakarta Sans',
    animation: 'slide-up',
    fontWeight: '600',
    borderRadius: 8,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 14,
    paddingRight: 14,
    description: 'Presenter name badge with glass backdrop',
  },
  {
    id: 'breaking-news',
    name: 'Breaking News Ticker',
    category: 'Badges',
    text: 'BREAKING NEWS // LIVE UPDATE',
    fontSize: 26,
    color: '#ffffff',
    backgroundColor: '#dc2626',
    fontFamily: 'Inter',
    animation: 'slide-right',
    fontWeight: '800',
    letterSpacing: 2,
    borderRadius: 4,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 14,
    paddingRight: 14,
    textTransform: 'uppercase',
    description: 'Urgent news broadcast ticker banner',
  },
  {
    id: 'callout-punchy',
    name: 'Action Callout Banner',
    category: 'Badges',
    text: 'NEW EPISODE OUT NOW!',
    fontSize: 44,
    color: '#fbbf24',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    fontFamily: 'Anton',
    animation: 'pop',
    fontWeight: '400',
    borderRadius: 6,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 16,
    paddingRight: 16,
    description: 'Attention grabbing alert banner',
  },
  {
    id: 'speaker-id-rounded',
    name: 'Speaker ID Pill',
    category: 'Badges',
    text: 'Dr. Elena Rostova · Lead Scientist',
    fontSize: 22,
    color: '#e2e8f0',
    backgroundColor: 'rgba(30, 41, 59, 0.9)',
    fontFamily: 'Outfit',
    animation: 'slide-up',
    fontWeight: '600',
    borderRadius: 20,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 16,
    paddingRight: 16,
    description: 'Rounded pill speaker identification badge',
  },
  {
    id: 'stream-watermark',
    name: 'Live Stream Watermark',
    category: 'Badges',
    text: 'LIVE STREAM ⏺ 1080p60',
    fontSize: 20,
    color: '#f87171',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    fontFamily: 'JetBrains Mono',
    animation: 'fade-in',
    fontWeight: '700',
    letterSpacing: 1,
    borderRadius: 4,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 10,
    paddingRight: 10,
    textTransform: 'uppercase',
    description: 'Compact broadcast status watermark',
  },
]

/**
 * Applies a typography preset's visual styling to an existing TextOverlay,
 * keeping the current text content unless none exists.
 */
export function applyTypographyPreset(
  current: Partial<TextOverlay> | undefined,
  preset: TextTypographyPreset,
  overrideText?: string,
): TextOverlay {
  const baseText = overrideText?.trim() || current?.text?.trim() || preset.text

  return {
    text: baseText,
    fontSize: preset.fontSize,
    fontFamily: preset.fontFamily,
    fontWeight: preset.fontWeight as any,
    fontStyle: preset.fontStyle ?? 'normal',
    color: preset.color,
    backgroundColor: preset.backgroundColor,
    textAlign: preset.textAlign ?? current?.textAlign ?? 'center',
    paddingTop: preset.paddingTop ?? 8,
    paddingBottom: preset.paddingBottom ?? 8,
    paddingLeft: preset.paddingLeft ?? 12,
    paddingRight: preset.paddingRight ?? 12,
    borderRadius: preset.borderRadius ?? 0,
    shadow: Boolean(preset.shadow),
    shadowColor: preset.shadowColor,
    shadowBlur: preset.shadowBlur,
    shadowOffsetX: preset.shadowOffsetX,
    shadowOffsetY: preset.shadowOffsetY,
    stroke: preset.stroke,
    letterSpacing: preset.letterSpacing ?? 0,
    lineHeight: preset.lineHeight ?? 1.2,
    textTransform: preset.textTransform ?? 'none',
    textDecoration: preset.textDecoration ?? 'none',
    animation: preset.animation,
    animationDuration: preset.animationDuration ?? 0.5,
  }
}

/**
 * Preloads all Google Fonts used across the typography presets.
 */
export function preloadAllTypographyPresetFonts(): void {
  const families = new Set<string>()
  for (const p of TEXT_TYPOGRAPHY_PRESETS) {
    families.add(p.fontFamily)
  }
  for (const family of families) {
    loadGoogleFont(family)
  }
}
